GET http://localhost:5250/blogs

###
POST http://localhost:5250/blogs
Content-Type: application/json

{
    "Title": "Third Blog",
    "Content": "This is the content of the third blog."
}

###
POST http://localhost:5250/blogs
Content-Type: application/json
X-API-KEY: ThisisaBadPassword

{
    "Title": "Third Blog",
    "Content": "This is the content of the third blog."
}