GET http://localhost:5002/users/10/posts/buffalo-wings

###

GET http://localhost:5002/products/-10

###

GET http://localhost:5002/report/

###

GET http://localhost:5002/files/images/cats/cat_1.jpg

###

GET http://localhost:5002/search?q=dotnet&page=2